# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

install:
  - pip install -e .[dev]
  - pip install coveralls

script:
  - py.test --doctest-modules --cov=doi src tests
  - mypy src/ tests
  - flake8 src/ tests
after_success:
  - coveralls
